- config.yaml
- themes/leo-fresh/layouts/partials/organisers.html
> add job titles

- config.yaml
- themes/leo-fresh/layouts/index.html
- themes/leo-fresh/layouts/partials/covid19.html
1. Provide Covid-19 update section. 
2. Landing button goes to "Read more" goes to this section. Important Update on landing page
I currently haven't removed any sections, wanted to run it by you first. As for the sections we might want to remove
- Key Dates
- Location
- Call for Papers
The changes are as simple as commenting out in the yaml.
> Covid 19 update

- components/home.jsx
- pages/team.jsx
> adding team json-ld

- components/home.jsx
> adding ticketing

- components/navbar.jsx
- pages/faq.jsx
> adding faq's

- components/home.jsx
- components/navbar.jsx
- pages/faq.jsx
> a few updates

- components/logos.jsx
> adding in aws

- components/hackathon.jsx
- components/home.jsx
- components/navbar.jsx
- pages/index.jsx
> feat: hackathon

- components/footer.jsx
- components/home.jsx
- components/navbar.jsx
- components/signup/updateProfile.jsx
- pages/blogs.js
- posts/2022-04/5-reasons-to-attend.mdx
> feat: a few nav updates

- .projenrc.js
- components/hackathon/hackSignUp.jsx
- next.config.js
- pages/_app.js
- pages/index.js
- utils/ga.js
> feat: adding hackathon form

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/upgrade-main.yml
- .projen/deps.json
- .projenrc.js
- components/hackathon/hackSignUp.jsx
- package-lock.json
- package.json
> feat: adding confetti

- components/sponsors/sponsorPricing.jsx
> feat: sponsor links

- next.config.js
- posts/2022-06-01/Build a simple data-lakehouse-with-fivetran-and-databricks.mdx
> feat: hackathon blog

- package-lock.json
- package.json
Ran npx projen to change package-lock and package
> fix: npx projen

- pages/privacy.js
Features Added:
- Privacy Page added from the Template.
- Some HTML tags not fixed as of yet.
- Generic layout used; need to be narrowed down based on our usage and policy
> Privacy page

- pages/forms/join-slack.js
Fixes #
- Added second page questionnaire. 
- Added code of conduct section with the corresponding link
Pending #
- Layout fixing pending
- Checkbox for Code of Conduct
> Slack form

- .projen/deps.json
- README.md
- components/citybar.jsx
- components/meetups.jsx
- graphql/meetup/fetchMeetups.js
- helpers/fetchMeetups.js
- package-lock.json
- package.json
- pages/meetup.js
1. Meetups component to display placeholder meetup information
2. Meetup page to pull the meetups component
> feat: meetup components

- pages/forms/join-slack.js
> fixed question fieldsets

- pages/forms/join-slack.js
Gradually adding new styles and behaviours to make the page pretty
> feat: page uplift

- data/2022/allData.json
> adding joe reis

- components/auth/register.jsx
- components/auth/sign-in.jsx
- components/navbar.jsx
- components/venues/melbourne.jsx
- components/venues/sydney.jsx
- pages/conference/melbourne.js
- pages/conference/sydney.js
Fixes #
Location Pages and signin / register error correction.
> Location pages

- data/2022/allData.json
Fixes #
Modified  allData.json
> feat: addData

- README.md
- pages/client-protected.js
> feat: fix image branch

- pages/scan.js
Revert code in scan.js to previous one to get the laptop front camera working atleast
> fix: revert scan.js changes

- data/2022/allData.json
> Update to Lizzie Reid's title

- src/components/conference/schedule.astro
- src/components/conference/sessionList.astro
Two tracks added with our own awesome design
1. Room 2 
2. Room 3
> feat: add two other tracks room 2 and room 3
